import datetime

# Import Libraries

import pandas as pd
import numpy as np



# for data splitting, transforming and model training
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV

# for model evaluation
from sklearn.metrics import classification_report, ConfusionMatrixDisplay
from sklearn.metrics import accuracy_score, classification_report

pd.set_option('display.max_columns', None)

from sklearn.preprocessing import OneHotEncoder

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

from sklearn.preprocessing import RobustScaler
from sklearn.preprocessing import StandardScaler
import boto3

import pickle

#Read dataset
churn_data_raw = pd.read_csv("Churn_raw_data.csv")

##################################################################################################################################################################################################################################################################
######################################___________Data_Preprocessing____________####################################################################################################################################################################################################################################################################################################################

# Define the columns to be one-hot encoded
columns_to_encode = ['SEATS_BIN', 'TENURE_BIN','Customer Segment']

# Initialize the OneHotEncoder with drop='first'
# encoder = OneHotEncoder(drop='first', sparse=False)
encoder = OneHotEncoder(drop='first',sparse_output=False)
# Fit the encoder on the data
encoder.fit(churn_data_raw[columns_to_encode])

# Transform the data
encoded_data = encoder.transform(churn_data_raw[columns_to_encode])

# Get the categories for each column
categories = encoder.categories_

# Generate meaningful column names
new_columns = []
for i, col in enumerate(columns_to_encode):
    for category in categories[i][1:]:
        new_columns.append(f"{col}_{category}")

# Create a dataframe with the encoded features
encoded_df = pd.DataFrame(encoded_data, columns=new_columns)


# Concatenate the original dataframe with the encoded features
result_df = pd.concat([churn_data_raw, encoded_df], axis=1)

# Drop the original categorical columns
result_df = result_df.drop(columns=columns_to_encode)

churn_data_raw=result_df

## Converting Parent ID into string
churn_data_raw['CHURN_MONTH'] = pd.to_datetime(churn_data_raw['MONTH_END_DATE'], format='%Y-%m-%d')
churn_data_raw[["Parent Account ID"]] = churn_data_raw[["Parent Account ID"]].astype(str)

## Removing high ARR customers
churn_data = churn_data_raw.loc[ # (churn_data_raw['END_MRR'] <= 1000) & 
                                (churn_data_raw['ARR'] <= 8000) & (churn_data_raw['END_MRR'] <= 700) & (churn_data_raw['END_YEAR'] >= 2021) ]

## Fill NAN
churn_data = churn_data.fillna(0)
def remove_outliers(df, fields):
    for field in fields:
        q1 = df[field].astype('float').quantile(0.25)
        q3 = df[field].astype('float').quantile(0.75)
        iqr = q3 - q1
        lower_bound = q1 - 3.5 * iqr
        upper_bound = q3 + 3.5 * iqr
        df = df.loc[(df[field] >= lower_bound) & (df[field] <= upper_bound)]
    return df

# Remove outliers from the three fields
churn_data = remove_outliers(churn_data, ['END_SEATS', 'END_MRR', 'UEX_COST_PER_SEAT',
                         'MEX_COST_PER_SEAT','MUEX_COST_PER_SEAT', 'ARR'
                         ])
new_cols=[]

for col in churn_data:
    if col.endswith('_CNT'):
        churn_data['AVG_' + col]= churn_data[col]/churn_data['AVG_ANNUAL_SEATS']
        new_cols.append('AVG_' + col)

    elif col.endswith('_CNT_60'):
        churn_data['AVG_' + col]= churn_data[col]/churn_data['AVG_2M_SEATS']
        new_cols.append('AVG_' + col)
new_cols=[]

for col in churn_data:
    if col.endswith('_CNT') and col not in ('END_BILLED_PROD_CNT','END_PROD_CNT','') and not col.startswith('AVG_') and not col.startswith('60D_AVG'):
        churn_data['60D_AVG_' + col]= churn_data[col+'_60']/churn_data[col]
        new_cols.append('60D_AVG_' + col)
        
## Fill NAN
churn_data = churn_data.fillna(0)

## Drop na
churn_data = churn_data.dropna()
churn_data = churn_data.reset_index(drop=True)
churn_data.replace([np.inf, -np.inf], 0, inplace=True)
## Create a list of the features

fields = ['Parent Account ID','END_YEAR',
                         'CHURN_CUST_FLAG','MANAGED_FLAG','PARTNER_SRC_IND', 'CONTRACT_FLAG',
                         #'END_SEATS',
                         #'TENURE_YRS',
                         'SEATS_BIN_11-50', 'SEATS_BIN_2-10','SEATS_BIN_51-100','SEATS_BIN_100+',
                         'TENURE_BIN_2-4', 'TENURE_BIN_5-8','TENURE_BIN_8+',
                         'Customer Segment_Micro','Customer Segment_Mid Market','Customer Segment_SMB',#'Customer Segment_Unassigned/CSM/AM',
                         'END_BILLED_PROD_CNT',	'UEX_COST_PER_SEAT',	'MEX_COST_PER_SEAT',	'MUEX_COST_PER_SEAT','NO_OF_EMP',#	'CUST_REVENUE',	
                         'DAYS_TO_NEXT_RENEWAL',
                         #'END_MRR',#'DOWNGRADE_ARR',  'UPGRADE_ARR', 'END_PROD_CNT'
                         'ARR', 'AVG_ANNUAL_SEATS', 'AVG_MRR', 
                         'AVG_DOWNGRADE_MRR', 'AVG_UPGRADE_MRR',
                         #'AVG_6M_MRR', 'AVG_6M_SEATS', 'AVG_6M_DOWNGRADE_MRR', 'AVG_6M_UPGRADE_MRR',
                         'AVG_3M_MRR', 'AVG_3M_SEATS', 'AVG_3M_DOWNGRADE_MRR', 'AVG_3M_UPGRADE_MRR', 
                         #'AVG_2M_SEATS',#'AVG_2M_MRR',
                         #'AVG_2M_SEATS_PERC','AVG_3M_SEATS_PERC','AVG_6M_SEATS_PERC',
                         #'AVG_2M_MRR_PERC','AVG_3M_MRR_PERC','AVG_6M_MRR_PERC',
                         'PERC_CHANGE_3M_1YR_DOWNGRADE_MRR','PERC_CHANGE_6M_1YR_DOWNGRADE_MRR',
                         'PERC_CHANGE_3M_1YR_UPGRADE_MRR','PERC_CHANGE_6M_1YR_UPGRADE_MRR',
                               
                               
                         
                        # Last 1 yr case data
                         'O_CHAT_RESOLVED_CNT', 'O_CHAT_WNB_RESOLVED_CNT', 'O_CHAT_CUST_UNRESP_CNT', 'O_CHAT_NOT_RESOLVED_CNT', 'O_PHONE_RESOLVED_CNT', 'O_PHONE_WNB_RESOLVED_CNT', 'O_PHONE_CUST_UNRESP_CNT', 'O_PHONE_NOT_RESOLVED_CNT', 'O_WEB_RESOLVED_CNT', 'O_WEB_WNB_RESOLVED_CNT', 'O_WEB_CUST_UNRESP_CNT', 'O_WEB_NOT_RESOLVED_CNT', 'O_OTHERS_RESOLVED_CNT', 'O_OTHERS_WNB_RESOLVED_CNT', 'O_OTHERS_CUST_UNRESP_CNT', 'O_OTHERS_NOT_RESOLVED_CNT', 
                         'CCC_BILLING_RESOLVED_CNT', 'CCC_BILLING_WNB_RESOLVED_CNT', 'CCC_BILLING_CUST_UNRESP_CNT', 'CCC_BILLING_NOT_RESOLVED_CNT', 'CCC_BUSINESS_CHANGES_RESOLVED_CNT', 'CCC_BUSINESS_CHANGES_WNB_RESOLVED_CNT', 'CCC_BUSINESS_CHANGES_UNRESP_CNT', 'CCC_BUSINESS_CHANGES_NOT_RESOLVED_CNT', 'CCC_BUSINESS_FAIL_RESOLVED_CNT', 'CCC_BUSINESS_FAIL_WNB_RESOLVED_CNT', 'CCC_BUSINESS_FAIL_UNRESP_CNT', 'CCC_BUSINESS_FAIL_NOT_RESOLVED_CNT', 
                         'CCC_DNME_RESOLVED_CNT', 'CCC_DNME_WNB_RESOLVED_CNT', 'CCC_DNME_UNRESP_CNT', 'CCC_DNME_NOT_RESOLVED_CNT', 'CCC_PRICE_RESOLVED_CNT', 'CCC_PRICE_WNB_RESOLVED_CNT', 'CCC_PRICE_UNRESP_CNT', 'CCC_PRICE_NOT_RESOLVED_CNT', 'CCC_FEATURE_RESOLVED_CNT', 'CCC_FEATURE_WNB_RESOLVED_CNT', 'CCC_FEATURE_UNRESP_CNT', 'CCC_FEATURE_NOT_RESOLVED_CNT', 'CCC_SS_RESOLVED_CNT', 'CCC_SS_WNB_RESOLVED_CNT', 'CCC_SS_UNRESP_CNT', 'CCC_SS_NOT_RESOLVED_CNT', 
                         'CCC_SO_RESOLVED_CNT', 'CCC_SO_WNB_RESOLVED_CNT', 'CCC_SO_UNRESP_CNT', 'CCC_SO_NOT_RESOLVED_CNT', 'CCC_QUALITY_RESOLVED_CNT', 'CCC_QUALITY_WNB_RESOLVED_CNT', 'CCC_QUALITY_UNRESP_CNT', 'CCC_QUALITY_NOT_RESOLVED_CNT', 'CCC_OTHERS_RESOLVED_CNT', 'CCC_OTHERS_WNB_RESOLVED_CNT', 'CCC_OTHERS_UNRESP_CNT', 'CCC_OTHERS_NOT_RESOLVED_CNT', 
                         'OVERALL_RESOLVED_CNT','OVERALL_WNB_RESOLVED_CNT','OVERALL_UNRESP_CNT','OVERALL_NOT_RESOLVED_CNT',
                         #'CC_BILLING_RESOLVED_CNT', 'CC_BILLING_WNB_RESOLVED_CNT', 'CC_BILLING_UNRESP_CNT', 'CC_BILLING_NOT_RESOLVED_CNT',
                         #'CC_CANCEL_INTENT_RESOLVED_CNT', 'CC_CANCEL_INTENT_WNB_RESOLVED_CNT', 'CC_CANCEL_INTENT_UNRESP_CNT', 'CC_CANCEL_INTENT_NOT_RESOLVED_CNT', 'CC_FEATURE_RESOLVED_CNT', 'CC_FEATURE_WNB_RESOLVED_CNT', 'CC_FEATURE_UNRESP_CNT', 'CC_FEATURE_NOT_RESOLVED_CNT', 'CC_HARDWARE_RESOLVED_CNT', 'CC_HARDWARE_WNB_RESOLVED_CNT', 'CC_HARDWARE_UNRESP_CNT', 'CC_HARDWARE_NOT_RESOLVED_CNT', 'CC_SOFTWARE_RESOLVED_CNT', 'CC_SOFTWARE_WNB_RESOLVED_CNT', 'CC_SOFTWARE_UNRESP_CNT', 'CC_SOFTWARE_NOT_RESOLVED_CNT', 
                         #'CC_TECHNICAL_RESOLVED_CNT', 'CC_TECHNICAL_WNB_RESOLVED_CNT', 'CC_TECHNICAL_UNRESP_CNT', 'CC_TECHNICAL_NOT_RESOLVED_CNT', 'CC_OTHERS_RESOLVED_CNT', 'CC_OTHERS_WNB_RESOLVED_CNT', 'CC_OTHERS_UNRESP_CNT', 'CC_OTHERS_NOT_RESOLVED_CNT', 
                         
                        # Last 2M case data
                        'O_CHAT_RESOLVED_CNT_60', 'O_CHAT_WNB_RESOLVED_CNT_60', 'O_CHAT_CUST_UNRESP_CNT_60', 'O_CHAT_NOT_RESOLVED_CNT_60', 'O_PHONE_RESOLVED_CNT_60', 'O_PHONE_WNB_RESOLVED_CNT_60', 'O_PHONE_CUST_UNRESP_CNT_60', 'O_PHONE_NOT_RESOLVED_CNT_60', 'O_WEB_RESOLVED_CNT_60', 'O_WEB_WNB_RESOLVED_CNT_60', 'O_WEB_CUST_UNRESP_CNT_60', 'O_WEB_NOT_RESOLVED_CNT_60', 'O_OTHERS_RESOLVED_CNT_60', 'O_OTHERS_WNB_RESOLVED_CNT_60', 'O_OTHERS_CUST_UNRESP_CNT_60', 'O_OTHERS_NOT_RESOLVED_CNT_60', 
                        'CCC_BILLING_RESOLVED_CNT_60', 'CCC_BILLING_WNB_RESOLVED_CNT_60', 'CCC_BILLING_CUST_UNRESP_CNT_60', 'CCC_BILLING_NOT_RESOLVED_CNT_60', 'CCC_BUSINESS_CHANGES_RESOLVED_CNT_60', 'CCC_BUSINESS_CHANGES_WNB_RESOLVED_CNT_60', 'CCC_BUSINESS_CHANGES_UNRESP_CNT_60', 'CCC_BUSINESS_CHANGES_NOT_RESOLVED_CNT_60', 'CCC_BUSINESS_FAIL_RESOLVED_CNT_60', 'CCC_BUSINESS_FAIL_WNB_RESOLVED_CNT_60', 'CCC_BUSINESS_FAIL_UNRESP_CNT_60', 'CCC_BUSINESS_FAIL_NOT_RESOLVED_CNT_60', 
                        'CCC_DNME_RESOLVED_CNT_60', 'CCC_DNME_WNB_RESOLVED_CNT_60', 'CCC_DNME_UNRESP_CNT_60', 'CCC_DNME_NOT_RESOLVED_CNT_60', 'CCC_PRICE_RESOLVED_CNT_60', 'CCC_PRICE_WNB_RESOLVED_CNT_60', 'CCC_PRICE_UNRESP_CNT_60', 'CCC_PRICE_NOT_RESOLVED_CNT_60', 'CCC_FEATURE_RESOLVED_CNT_60', 'CCC_FEATURE_WNB_RESOLVED_CNT_60', 'CCC_FEATURE_UNRESP_CNT_60', 'CCC_FEATURE_NOT_RESOLVED_CNT_60', 'CCC_SS_RESOLVED_CNT_60', 'CCC_SS_WNB_RESOLVED_CNT_60', 'CCC_SS_UNRESP_CNT_60', 'CCC_SS_NOT_RESOLVED_CNT_60', 
                        'CCC_SO_RESOLVED_CNT_60', 'CCC_SO_WNB_RESOLVED_CNT_60', 'CCC_SO_UNRESP_CNT_60', 'CCC_SO_NOT_RESOLVED_CNT_60', 'CCC_QUALITY_RESOLVED_CNT_60', 'CCC_QUALITY_WNB_RESOLVED_CNT_60', 'CCC_QUALITY_UNRESP_CNT_60', 'CCC_QUALITY_NOT_RESOLVED_CNT_60', 'CCC_OTHERS_RESOLVED_CNT_60', 'CCC_OTHERS_WNB_RESOLVED_CNT_60', 'CCC_OTHERS_UNRESP_CNT_60', 'CCC_OTHERS_NOT_RESOLVED_CNT_60', 'CC_BILLING_RESOLVED_CNT_60', 
                        'OVERALL_RESOLVED_CNT_60','OVERALL_WNB_RESOLVED_CNT_60','OVERALL_UNRESP_CNT_60','OVERALL_NOT_RESOLVED_CNT_60',
                        #'CC_BILLING_WNB_RESOLVED_CNT_60', 'CC_BILLING_UNRESP_CNT_60', 'CC_BILLING_NOT_RESOLVED_CNT_60', 
                        #'CC_CANCEL_INTENT_RESOLVED_CNT_60', 'CC_CANCEL_INTENT_WNB_RESOLVED_CNT_60', 'CC_CANCEL_INTENT_UNRESP_CNT_60', 'CC_CANCEL_INTENT_NOT_RESOLVED_CNT_60', 'CC_FEATURE_RESOLVED_CNT_60', 'CC_FEATURE_WNB_RESOLVED_CNT_60', 'CC_FEATURE_UNRESP_CNT_60', 'CC_FEATURE_NOT_RESOLVED_CNT_60', 'CC_HARDWARE_RESOLVED_CNT_60', 'CC_HARDWARE_WNB_RESOLVED_CNT_60', 'CC_HARDWARE_UNRESP_CNT_60', 'CC_HARDWARE_NOT_RESOLVED_CNT_60', 'CC_SOFTWARE_RESOLVED_CNT_60', 'CC_SOFTWARE_WNB_RESOLVED_CNT_60', 'CC_SOFTWARE_UNRESP_CNT_60', 'CC_SOFTWARE_NOT_RESOLVED_CNT_60', 
                        #'CC_TECHNICAL_RESOLVED_CNT_60', 'CC_TECHNICAL_WNB_RESOLVED_CNT_60', 'CC_TECHNICAL_UNRESP_CNT_60', 'CC_TECHNICAL_NOT_RESOLVED_CNT_60', 'CC_OTHERS_RESOLVED_CNT_60', 'CC_OTHERS_WNB_RESOLVED_CNT_60', 'CC_OTHERS_UNRESP_CNT_60', 'CC_OTHERS_NOT_RESOLVED_CNT_60', 

                         
                        # Last 1 yr AVG case data
                        #'AVG_O_CHAT_RESOLVED_CNT', 'AVG_O_CHAT_WNB_RESOLVED_CNT', 'AVG_O_CHAT_CUST_UNRESP_CNT', 'AVG_O_CHAT_NOT_RESOLVED_CNT', 'AVG_O_PHONE_RESOLVED_CNT', 'AVG_O_PHONE_WNB_RESOLVED_CNT', 'AVG_O_PHONE_CUST_UNRESP_CNT', 'AVG_O_PHONE_NOT_RESOLVED_CNT', 'AVG_O_WEB_RESOLVED_CNT', 'AVG_O_WEB_WNB_RESOLVED_CNT', 'AVG_O_WEB_CUST_UNRESP_CNT', 'AVG_O_WEB_NOT_RESOLVED_CNT', 'AVG_O_OTHERS_RESOLVED_CNT', 'AVG_O_OTHERS_WNB_RESOLVED_CNT', 'AVG_O_OTHERS_CUST_UNRESP_CNT', 'AVG_O_OTHERS_NOT_RESOLVED_CNT', 
                        #'AVG_CCC_BILLING_RESOLVED_CNT', 'AVG_CCC_BILLING_WNB_RESOLVED_CNT', 'AVG_CCC_BILLING_CUST_UNRESP_CNT', 'AVG_CCC_BILLING_NOT_RESOLVED_CNT', 'AVG_CCC_BUSINESS_CHANGES_RESOLVED_CNT', 'AVG_CCC_BUSINESS_CHANGES_WNB_RESOLVED_CNT', 'AVG_CCC_BUSINESS_CHANGES_UNRESP_CNT', 'AVG_CCC_BUSINESS_CHANGES_NOT_RESOLVED_CNT', 'AVG_CCC_BUSINESS_FAIL_RESOLVED_CNT', 'AVG_CCC_BUSINESS_FAIL_WNB_RESOLVED_CNT', 'AVG_CCC_BUSINESS_FAIL_UNRESP_CNT', 'AVG_CCC_BUSINESS_FAIL_NOT_RESOLVED_CNT', 
                        #'AVG_CCC_DNME_RESOLVED_CNT', 'AVG_CCC_DNME_WNB_RESOLVED_CNT', 'AVG_CCC_DNME_UNRESP_CNT', 'AVG_CCC_DNME_NOT_RESOLVED_CNT', 'AVG_CCC_PRICE_RESOLVED_CNT', 'AVG_CCC_PRICE_WNB_RESOLVED_CNT', 'AVG_CCC_PRICE_UNRESP_CNT', 'AVG_CCC_PRICE_NOT_RESOLVED_CNT', 'AVG_CCC_FEATURE_RESOLVED_CNT', 'AVG_CCC_FEATURE_WNB_RESOLVED_CNT', 'AVG_CCC_FEATURE_UNRESP_CNT', 'AVG_CCC_FEATURE_NOT_RESOLVED_CNT', 'AVG_CCC_SS_RESOLVED_CNT', 'AVG_CCC_SS_WNB_RESOLVED_CNT', 'AVG_CCC_SS_UNRESP_CNT', 'AVG_CCC_SS_NOT_RESOLVED_CNT', 
                        #'AVG_CCC_SO_RESOLVED_CNT', 'AVG_CCC_SO_WNB_RESOLVED_CNT', 'AVG_CCC_SO_UNRESP_CNT', 'AVG_CCC_SO_NOT_RESOLVED_CNT', 'AVG_CCC_QUALITY_RESOLVED_CNT', 'AVG_CCC_QUALITY_WNB_RESOLVED_CNT', 'AVG_CCC_QUALITY_UNRESP_CNT', 'AVG_CCC_QUALITY_NOT_RESOLVED_CNT', 'AVG_CCC_OTHERS_RESOLVED_CNT', 'AVG_CCC_OTHERS_WNB_RESOLVED_CNT', 'AVG_CCC_OTHERS_UNRESP_CNT', 'AVG_CCC_OTHERS_NOT_RESOLVED_CNT', 'AVG_CC_BILLING_RESOLVED_CNT', 'AVG_CC_BILLING_WNB_RESOLVED_CNT', 'AVG_CC_BILLING_UNRESP_CNT', 'AVG_CC_BILLING_NOT_RESOLVED_CNT',
                        #'AVG_CC_CANCEL_INTENT_RESOLVED_CNT', 'AVG_CC_CANCEL_INTENT_WNB_RESOLVED_CNT', 'AVG_CC_CANCEL_INTENT_UNRESP_CNT', 'AVG_CC_CANCEL_INTENT_NOT_RESOLVED_CNT', 'AVG_CC_FEATURE_RESOLVED_CNT', 'AVG_CC_FEATURE_WNB_RESOLVED_CNT', 'AVG_CC_FEATURE_UNRESP_CNT', 'AVG_CC_FEATURE_NOT_RESOLVED_CNT', 'AVG_CC_HARDWARE_RESOLVED_CNT', 'AVG_CC_HARDWARE_WNB_RESOLVED_CNT', 'AVG_CC_HARDWARE_UNRESP_CNT', 'AVG_CC_HARDWARE_NOT_RESOLVED_CNT', 'AVG_CC_SOFTWARE_RESOLVED_CNT', 'AVG_CC_SOFTWARE_WNB_RESOLVED_CNT', 'AVG_CC_SOFTWARE_UNRESP_CNT', 'AVG_CC_SOFTWARE_NOT_RESOLVED_CNT', 
                        #'AVG_CC_TECHNICAL_RESOLVED_CNT', 'AVG_CC_TECHNICAL_WNB_RESOLVED_CNT', 'AVG_CC_TECHNICAL_UNRESP_CNT', 'AVG_CC_TECHNICAL_NOT_RESOLVED_CNT', 'AVG_CC_OTHERS_RESOLVED_CNT', 'AVG_CC_OTHERS_WNB_RESOLVED_CNT', 'AVG_CC_OTHERS_UNRESP_CNT', 'AVG_CC_OTHERS_NOT_RESOLVED_CNT', 
                         
                         # Last 2M AVG case data
                        #'AVG_O_CHAT_RESOLVED_CNT_60', 'AVG_O_CHAT_WNB_RESOLVED_CNT_60', 'AVG_O_CHAT_CUST_UNRESP_CNT_60', 'AVG_O_CHAT_NOT_RESOLVED_CNT_60', 'AVG_O_PHONE_RESOLVED_CNT_60', 'AVG_O_PHONE_WNB_RESOLVED_CNT_60', 'AVG_O_PHONE_CUST_UNRESP_CNT_60', 'AVG_O_PHONE_NOT_RESOLVED_CNT_60', 'AVG_O_WEB_RESOLVED_CNT_60', 'AVG_O_WEB_WNB_RESOLVED_CNT_60', 'AVG_O_WEB_CUST_UNRESP_CNT_60', 'AVG_O_WEB_NOT_RESOLVED_CNT_60', 'AVG_O_OTHERS_RESOLVED_CNT_60', 'AVG_O_OTHERS_WNB_RESOLVED_CNT_60', 'AVG_O_OTHERS_CUST_UNRESP_CNT_60', 'AVG_O_OTHERS_NOT_RESOLVED_CNT_60', 
                        #'AVG_CCC_BILLING_RESOLVED_CNT_60', 'AVG_CCC_BILLING_WNB_RESOLVED_CNT_60', 'AVG_CCC_BILLING_CUST_UNRESP_CNT_60', 'AVG_CCC_BILLING_NOT_RESOLVED_CNT_60', 'AVG_CCC_BUSINESS_CHANGES_RESOLVED_CNT_60', 'AVG_CCC_BUSINESS_CHANGES_WNB_RESOLVED_CNT_60', 'AVG_CCC_BUSINESS_CHANGES_UNRESP_CNT_60', 'AVG_CCC_BUSINESS_CHANGES_NOT_RESOLVED_CNT_60', 'AVG_CCC_BUSINESS_FAIL_RESOLVED_CNT_60', 'AVG_CCC_BUSINESS_FAIL_WNB_RESOLVED_CNT_60', 'AVG_CCC_BUSINESS_FAIL_UNRESP_CNT_60', 'AVG_CCC_BUSINESS_FAIL_NOT_RESOLVED_CNT_60', 
                        #'AVG_CCC_DNME_RESOLVED_CNT_60', 'AVG_CCC_DNME_WNB_RESOLVED_CNT_60', 'AVG_CCC_DNME_UNRESP_CNT_60', 'AVG_CCC_DNME_NOT_RESOLVED_CNT_60', 'AVG_CCC_PRICE_RESOLVED_CNT_60', 'AVG_CCC_PRICE_WNB_RESOLVED_CNT_60', 'AVG_CCC_PRICE_UNRESP_CNT_60', 'AVG_CCC_PRICE_NOT_RESOLVED_CNT_60', 'AVG_CCC_FEATURE_RESOLVED_CNT_60', 'AVG_CCC_FEATURE_WNB_RESOLVED_CNT_60', 'AVG_CCC_FEATURE_UNRESP_CNT_60', 'AVG_CCC_FEATURE_NOT_RESOLVED_CNT_60', 'AVG_CCC_SS_RESOLVED_CNT_60', 'AVG_CCC_SS_WNB_RESOLVED_CNT_60', 'AVG_CCC_SS_UNRESP_CNT_60', 'AVG_CCC_SS_NOT_RESOLVED_CNT_60', 
                        #'AVG_CCC_SO_RESOLVED_CNT_60', 'AVG_CCC_SO_WNB_RESOLVED_CNT_60', 'AVG_CCC_SO_UNRESP_CNT_60', 'AVG_CCC_SO_NOT_RESOLVED_CNT_60', 'AVG_CCC_QUALITY_RESOLVED_CNT_60', 'AVG_CCC_QUALITY_WNB_RESOLVED_CNT_60', 'AVG_CCC_QUALITY_UNRESP_CNT_60', 'AVG_CCC_QUALITY_NOT_RESOLVED_CNT_60', 'AVG_CCC_OTHERS_RESOLVED_CNT_60', 'AVG_CCC_OTHERS_WNB_RESOLVED_CNT_60', 'AVG_CCC_OTHERS_UNRESP_CNT_60', 'AVG_CCC_OTHERS_NOT_RESOLVED_CNT_60', 'AVG_CC_BILLING_RESOLVED_CNT_60', 'AVG_CC_BILLING_WNB_RESOLVED_CNT_60', 'AVG_CC_BILLING_UNRESP_CNT_60', 'AVG_CC_BILLING_NOT_RESOLVED_CNT_60', 
                        #'AVG_CC_CANCEL_INTENT_RESOLVED_CNT_60', 'AVG_CC_CANCEL_INTENT_WNB_RESOLVED_CNT_60', 'AVG_CC_CANCEL_INTENT_UNRESP_CNT_60', 'AVG_CC_CANCEL_INTENT_NOT_RESOLVED_CNT_60', 'AVG_CC_FEATURE_RESOLVED_CNT_60', 'AVG_CC_FEATURE_WNB_RESOLVED_CNT_60', 'AVG_CC_FEATURE_UNRESP_CNT_60', 'AVG_CC_FEATURE_NOT_RESOLVED_CNT_60', 'AVG_CC_HARDWARE_RESOLVED_CNT_60', 'AVG_CC_HARDWARE_WNB_RESOLVED_CNT_60', 'AVG_CC_HARDWARE_UNRESP_CNT_60', 'AVG_CC_HARDWARE_NOT_RESOLVED_CNT_60', 'AVG_CC_SOFTWARE_RESOLVED_CNT_60', 'AVG_CC_SOFTWARE_WNB_RESOLVED_CNT_60', 'AVG_CC_SOFTWARE_UNRESP_CNT_60', 'AVG_CC_SOFTWARE_NOT_RESOLVED_CNT_60', 
                        #'AVG_CC_TECHNICAL_RESOLVED_CNT_60', 'AVG_CC_TECHNICAL_WNB_RESOLVED_CNT_60', 'AVG_CC_TECHNICAL_UNRESP_CNT_60', 'AVG_CC_TECHNICAL_NOT_RESOLVED_CNT_60', 'AVG_CC_OTHERS_RESOLVED_CNT_60', 'AVG_CC_OTHERS_WNB_RESOLVED_CNT_60', 'AVG_CC_OTHERS_UNRESP_CNT_60', 'AVG_CC_OTHERS_NOT_RESOLVED_CNT_60', 

                         ## Avg CES Score
                        #'AVG_ADOPTION_SCORE', 'AVG_LAST_MONTH_ADOPTION_SCORE', 'AVG_SECOND_LAST_MONTH_ADOPTION_SCORE', 'AVG_ENGAGEMENT_SCORE', 'AVG_LAST_MONTH_ENGAGEMENT_SCORE', 'AVG_SECOND_LAST_MONTH_ENGAGEMENT_SCORE', 'AVG_STICKINESS_SCORE', 'AVG_LAST_MONTH_STICKINESS_SCORE', 'AVG_SECOND_LAST_MONTH_STICKINESS_SCORE', 
                        #'AVG_CALL_ENGAGEMENT_SCORE', 'AVG_LAST_MONTH_CALL_ENGAGEMENT_SCORE', 'AVG_SECOND_LAST_MONTH_CALL_ENGAGEMENT_SCORE', 'AVG_CALL_STICKINESS_SCORE', 'AVG_LAST_MONTH_CALL_STICKINESS_SCORE', 'AVG_SECOND_LAST_MONTH_CALL_STICKINESS_SCORE', 'AVG_CALL_ADOPTION_SCORE', 'AVG_LAST_MONTH_CALL_ADOPTION_SCORE', 'AVG_SECOND_LAST_MONTH_CALL_ADOPTION_SCORE',
                        #'AVG_MESSAGING_ENGAGEMENT_SCORE', 'AVG_LAST_MONTH_MESSAGING_ENGAGEMENT_SCORE', 'AVG_SECOND_LAST_MONTH_MESSAGING_ENGAGEMENT_SCORE', 'AVG_MESSAGING_STICKINESS_SCORE', 'AVG_LAST_MONTH_MESSAGING_STICKINESS_SCORE', 'AVG_SECOND_LAST_MONTH_MESSAGING_STICKINESS_SCORE', 'AVG_MESSAGING_ADOPTION_SCORE', 'AVG_LAST_MONTH_MESSAGING_ADOPTION_SCORE', 'AVG_SECOND_LAST_MONTH_MESSAGING_ADOPTION_SCORE', 
                        #'AVG_MEETINGS_ENGAGEMENT_SCORE', 'AVG_LAST_MONTH_MEETINGS_ENGAGEMENT_SCORE', 'AVG_SECOND_LAST_MONTH_MEETINGS_ENGAGEMENT_SCORE', 'AVG_MEETINGS_STICKINESS_SCORE', 'AVG_LAST_MONTH_MEETINGS_STICKINESS_SCORE', 'AVG_SECOND_LAST_MONTH_MEETINGS_STICKINESS_SCORE', 'AVG_MEETINGS_ADOPTION_SCORE', 'AVG_LAST_MONTH_MEETINGS_ADOPTION_SCORE', 'AVG_SECOND_LAST_MONTH_MEETINGS_ADOPTION_SCORE', 
                         
                       # Max CES Score
                       'MIN_ADOPTION_SCORE', #'MIN_LAST_MONTH_ADOPTION_SCORE', 'MIN_SECOND_LAST_MONTH_ADOPTION_SCORE',
                       #'MIN_ENGAGEMENT_SCORE', 'MIN_LAST_MONTH_ENGAGEMENT_SCORE', 'MIN_SECOND_LAST_MONTH_ENGAGEMENT_SCORE',
                       'MIN_STICKINESS_SCORE', #'MIN_LAST_MONTH_STICKINESS_SCORE', 'MIN_SECOND_LAST_MONTH_STICKINESS_SCORE',
                       #'MIN_CALL_ENGAGEMENT_SCORE', 'MIN_LAST_MONTH_CALL_ENGAGEMENT_SCORE', 'MIN_SECOND_LAST_MONTH_CALL_ENGAGEMENT_SCORE',
                       #'MIN_CALL_STICKINESS_SCORE', 'MIN_LAST_MONTH_CALL_STICKINESS_SCORE', 'MIN_SECOND_LAST_MONTH_CALL_STICKINESS_SCORE',
                       #'MIN_CALL_ADOPTION_SCORE', 'MIN_LAST_MONTH_CALL_ADOPTION_SCORE', 'MIN_SECOND_LAST_MONTH_CALL_ADOPTION_SCORE',
                       'MIN_MESSAGING_ENGAGEMENT_SCORE', #'MIN_LAST_MONTH_MESSAGING_ENGAGEMENT_SCORE', 'MIN_SECOND_LAST_MONTH_MESSAGING_ENGAGEMENT_SCORE',
                       #'MIN_MESSAGING_STICKINESS_SCORE', 'MIN_LAST_MONTH_MESSAGING_STICKINESS_SCORE', 'MIN_SECOND_LAST_MONTH_MESSAGING_STICKINESS_SCORE',
                       #'MIN_MESSAGING_ADOPTION_SCORE', 'MIN_LAST_MONTH_MESSAGING_ADOPTION_SCORE', 'MIN_SECOND_LAST_MONTH_MESSAGING_ADOPTION_SCORE',
                       'MIN_MEETINGS_ENGAGEMENT_SCORE', #'MIN_LAST_MONTH_MEETINGS_ENGAGEMENT_SCORE', 'MIN_SECOND_LAST_MONTH_MEETINGS_ENGAGEMENT_SCORE',
                       #'MIN_MEETINGS_STICKINESS_SCORE', 'MIN_LAST_MONTH_MEETINGS_STICKINESS_SCORE', 'MIN_SECOND_LAST_MONTH_MEETINGS_STICKINESS_SCORE',
                       #'MIN_MEETINGS_ADOPTION_SCORE', 'MIN_LAST_MONTH_MEETINGS_ADOPTION_SCORE', 'MIN_SECOND_LAST_MONTH_MEETINGS_ADOPTION_SCORE',
                      
                       ## Difference in CES score last 2 months
                       #'AVG_ADOPTION_SCORE_DIFF1',  'AVG_ADOPTION_SCORE_DIFF2', 'AVG_ENGAGEMENT_SCORE_DIFF1', 'AVG_ENGAGEMENT_SCORE_DIFF2', 'AVG_STICKINESS_SCORE_DIFF1', 'AVG_STICKINESS_SCORE_DIFF2',
                       #'AVG_CALL_ENGAGEMENT_SCORE_DIFF1', 'AVG_CALL_ENGAGEMENT_SCORE_DIFF2',  'AVG_CALL_STICK_SCORE_DIFF1', 'AVG_CALL_STICK_SCORE_DIFF2', 'AVG_CALL_ADOPTION_SCORE_DIFF1',  'AVG_CALL_ADOPTION_SCORE_DIFF2', 
                       #'AVG_MES_ENG_SCORE_DIFF1', 'AVG_MES_ENG_SCORE_DIFF2',  'AVG_MES_STICK_SCORE_DIFF1',  'AVG_MES_STICK_SCORE_DIFF2',  'AVG_MES_ADOPTION_SCORE_DIFF1', 'AVG_MES_ADOPTION_SCORE_DIFF2',
                       #'AVG_MEETINGS_ENGAGEMENT_SCORE_DIFF1', 'AVG_MEETINGS_ENGAGEMENT_SCORE_DIFF2',  'AVG_MEETINGS_STICKINESS_SCORE_DIFF1',  'AVG_MEETINGS_STICKINESS_SCORE_DIFF2',  'AVG_MEETINGS_ADOPTION_SCORE_DIFF1',  'AVG_MEETINGS_ADOPTION_SCORE_DIFF2', 
                      
                       'MIN_ADOPTION_SCORE_DIFF1', 'MIN_ADOPTION_SCORE_DIFF2',
                       #'MIN_ENGAGEMENT_SCORE_DIFF1',  'MIN_ENGAGEMENT_SCORE_DIFF2',
                       'MIN_STICKINESS_SCORE_DIFF1', 'MIN_STICKINESS_SCORE_DIFF2',
                       #'MIN_CALL_ENGAGEMENT_SCORE_DIFF1', 'MIN_CALL_ENGAGEMENT_SCORE_DIFF2',
                       #'MIN_CALL_STICK_SCORE_DIFF1',  'MIN_CALL_STICK_SCORE_DIFF2',
                       #'MIN_CALL_ADOPTION_SCORE_DIFF1', 'MIN_CALL_ADOPTION_SCORE_DIFF2', 
                       'MIN_MES_ENG_SCORE_DIFF1',  'MIN_MES_ENG_SCORE_DIFF2',
                       #'MIN_MES_STICK_SCORE_DIFF1', 'MIN_MES_STICK_SCORE_DIFF2',
                       #'MIN_MES_ADOPTION_SCORE_DIFF1',  'MIN_MES_ADOPTION_SCORE_DIFF2',
                       'MIN_MEETINGS_ENGAGEMENT_SCORE_DIFF1',  'MIN_MEETINGS_ENGAGEMENT_SCORE_DIFF2',
                       #'MIN_MEETINGS_STICKINESS_SCORE_DIFF1', 'MIN_MEETINGS_STICKINESS_SCORE_DIFF2',
                       #'MIN_MEETINGS_ADOPTION_SCORE_DIFF1', 'MIN_MEETINGS_ADOPTION_SCORE_DIFF2'

                        #CALLS USAGE DATA
                        'AVG_TOTAL_CALLS_1YR','AVG_TOTAL_CALLS_3M','PERC_AVG_TOTAL_CALLS_3M','PERC_AVG_TOTAL_CALLS_6M','CALLS_DIFF1','CALLS_DIFF2','CALLS_DIFF3',
                        'AVG_BAD_CALLS_1YR','AVG_BAD_CALLS_3M','PERC_AVG_BAD_CALLS_1YR','PERC_AVG_BAD_CALLS_3M','PERC_AVG_BAD_CALLS_6M','BAD_CALLS_DIFF1','BAD_CALLS_DIFF2',
                        'PERC_CHANGE_3M_1YR_CALLS','PERC_CHANGE_6M_1YR_CALLS','PERC_CHANGE_3M_6M_CALLS',
                        'CURR_MONTH_CALLS','PREV_1MONTH_CALLS','PREV_2MONTH_CALLS',
                        #'TOTAL_CALLS_DURATION_1YR','PERC_AVG_CALLS_DUARATION_3M','PERC_AVG_CALLS_DUARATION_6M',
                        #'AVG_CALLS_DUARATION_6M','AVG_CALLS_DUARATION_3M','PERC_AVG_CALLS_DUARATION_3M','PERC_AVG_CALLS_DUARATION_6M',
                        #'AVG_CALLS_DUARATION_1YR','AVG_CALLS_DUARATION_3M','AVG_TOTAL_CALLS_6M',
                        #'PERC_AVG_BAD_CALLS_6M','AVG_BAD_CALLS_6M',
                        'OUTBOUND_CALLS_DIFF1','OUTBOUND_CALLS_DIFF2','OUTBOUND_CALLS_DIFF3','PERC_CHANGE_3M_1YR_OUTBOUND_CALLS','PERC_CHANGE_6M_1YR_OUTBOUND_CALLS','PERC_CHANGE_3M_6M_OUTBOUND_CALLS',
                        
                         #MESSAGES USAGE DATA
                        #'AVG_TOTAL_MMS_1YR','AVG_TOTAL_MMS_3M','MMS_DIFF1','MMS_DIFF2',
                        'AVG_TOTAL_SMS_1YR','AVG_TOTAL_SMS_3M','SMS_DIFF1','SMS_DIFF2',
                        #'AVG_TOTAL_BUSINESS_INBOX_1YR','AVG_TOTAL_BUSINESS_INBOX_3M','BUSINESS_INBOX_DIFF1','BUSINESS_INBOX_DIFF2',
                        'PERC_CHANGE_3M_1YR_SMS','PERC_CHANGE_6M_1YR_SMS','PERC_CHANGE_3M_6M_SMS',
                        'CURR_MONTH_MMS','PREV_1MONTH_MMS','PREV_2MONTH_SMS',
                        #'PERC_CHANGE_3M_1YR_MMS','PERC_CHANGE_6M_1YR_MMS','PERC_CHANGE_3M_6M_MMS',
                        #'TOTAL_MMS_1YR','CURR_MONTH_MMS','PREV_1MONTH_MMS','PREV_2MONTH_MMS','AVG_TOTAL_MMS_6M',
                        #'TOTAL_SMS_1YR','CURR_MONTH_SMS','PREV_1MONTH_SMS','PREV_2MONTH_SMS','AVG_TOTAL_SMS_6M',
                        #'TOTAL_BUSINESS_INBOX_1YR','CURR_MONTH_BUSINESS_INBOX','PREV_1MONTH_BUSINESS_INBOX','PREV_2MONTH_BUSINESS_INBOX',AVG_TOTAL_BUSINESS_INBOX_6M'
                        

                        #MESSAGES USAGE DATA
                        #'TOTAL_MMS_1YR','CURR_MONTH_MMS','PREV_1MONTH_MMS','PREV_2MONTH_MMS','MMS_DIFF1','MMS_DIFF2',
                        #'TOTAL_SMS_1YR','CURR_MONTH_SMS','PREV_1MONTH_SMS','PREV_2MONTH_SMS','SMS_DIFF1','SMS_DIFF2',
                        #'TOTAL_BUSINESS_INBOX_1YR','CURR_MONTH_BUSINESS_INBOX','PREV_1MONTH_BUSINESS_INBOX','PREV_2MONTH_BUSINESS_INBOX','BUSINESS_INBOX_DIFF1','BUSINESS_INBOX_DIFF2',
                        #'AVG_TOTAL_MMS_1YR','AVG_TOTAL_MMS_6M','AVG_TOTAL_MMS_3M','AVG_TOTAL_SMS_1YR','AVG_TOTAL_SMS_6M','AVG_TOTAL_SMS_3M','AVG_TOTAL_BUSINESS_INBOX_1YR','AVG_TOTAL_BUSINESS_INBOX_6M','AVG_TOTAL_BUSINESS_INBOX_3M'
                        
                        #MEETINGS DATA
                        'AVG_TOTAL_MEETINGS_1YR','AVG_TOTAL_MEETINGS_3M','MEETINGS_DIFF1','MEETINGS_DIFF2',
                        #'AVG_TOTAL_USERS_1YR','AVG_TOTAL_USERS_3M','MEETING_USERS_DIFF1','MEETING_USERS_DIFF2',
                        'PERC_CHANGE_3M_1YR_MEETINGS','PERC_CHANGE_6M_1YR_MEETINGS','PERC_CHANGE_3M_6M_MEETINGS',
                        'CURR_MONTH_MEETINGS','PREV_1MONTH_MEETINGS','PREV_2MONTH_MEETINGS',
                        #'TOTAL_MEETINGS_1YR','CURR_MONTH_MEETINGS','PREV_1MONTH_MEETINGS','PREV_2MONTH_MEETINGS','AVG_TOTAL_MEETINGS_6M',
                        #'CURR_MONTH_MEETING_DURATION','PREV_1MONTH_MEETING_DURATION','PREV_2MONTH_MEETING_DURATION','AVG_TOTAL_DURATION_6M','TOTAL_MEETING_DURATION_1YR',
                        #'CURR_MONTH_MEETING_USERS','PREV_1MONTH_MEETING_USERS','PREV_2MONTH_MEETING_USERS','TOTAL_MEETING_USERS_1YR','AVG_TOTAL_USERS_6M',

                        'CASE_REPEAT_FLAG_7_DAYS_1YR','CASE_REPEAT_FLAG_7_DAYS_6M','CASE_REPEAT_FLAG_7_DAYS_3M',
                        #'CASE_REPEAT_FLAG_30_DAYS_1YR','CASE_REPEAT_FLAG_30_DAYS_6M','CASE_REPEAT_FLAG_30_DAYS_3M',
                        'AVG_CASE_HANDLE_TIME_1YR','AVG_CASE_HANDLE_TIME_6M','AVG_CASE_HANDLE_TIME_3M',
                        'RETENTION_CALL_INDICATOR_1YR','RETENTION_CALL_INDICATOR_6M','RETENTION_CALL_INDICATOR_3M',

                        'SEV1_1YR','SEV1_6M','SEV1_3M','SEV2_1YR','SEV2_6M','SEV2_3M','SEV3_1YR','SEV3_6M','SEV3_3M',

                        'PERC_CHANGE_3M_1YR_ADOPTION_SCORE','PERC_CHANGE_6M_1YR_ADOPTION_SCORE','PERC_CHANGE_3M_6M_ADOPTION_SCORE',
                        'PERC_CHANGE_3M_1YR_STICKINESS_SCORE','PERC_CHANGE_6M_1YR_STICKINESS_SCORE','PERC_CHANGE_3M_6M_STICKINESS_SCORE',
                        'PERC_CHANGE_3M_1YR_MESSAGING_ENGAGEMENT_SCORE','PERC_CHANGE_6M_1YR_MESSAGING_ENGAGEMENT_SCORE','PERC_CHANGE_3M_6M_MESSAGING_ENGAGEMENT_SCORE',
                        'PERC_CHANGE_3M_1YR_MEETINGS_ENGAGEMENT_SCORE_SCORE','PERC_CHANGE_6M_1YR_MEETINGS_ENGAGEMENT_SCORE_SCORE','PERC_CHANGE_3M_6M_MEETINGS_ENGAGEMENT_SCORE_SCORE'

                                                
]

churn_data_model=churn_data[fields]
churn_data_model = churn_data_model.set_index(['Parent Account ID','END_YEAR'])

for column in churn_data_model.select_dtypes(include=['object']):
    try:
        # Attempt to convert to int
        churn_data_model[column] = churn_data_model[column].astype(float)
    except ValueError:
        try:
            # Attempt to convert to float if int conversion fails
            churn_data_model[column] = churn_data_model[column].astype(float)
        except ValueError:
            # If both conversions fail, handle it as needed (e.g., by cleaning or imputing data)
            pass


##################################################################################################################################################################################################################################################################
######################################___________Working_with_Model____________####################################################################################################################################################################################################################################################################################################################


X = churn_data_model.drop('CHURN_CUST_FLAG', axis=1)
X = X.apply(pd.to_numeric)
y = churn_data_model['CHURN_CUST_FLAG']

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=23)

# making a ColumnTransformer object
ct = ColumnTransformer(
    [('scaler', StandardScaler(), [
                         #'END_SEATS',
                         #'TENURE_YRS',
                         'SEATS_BIN_11-50', 'SEATS_BIN_2-10','SEATS_BIN_51-100','SEATS_BIN_100+',
                         'TENURE_BIN_2-4', 'TENURE_BIN_5-8','TENURE_BIN_8+',
                         'END_BILLED_PROD_CNT','UEX_COST_PER_SEAT','MEX_COST_PER_SEAT','MUEX_COST_PER_SEAT','NO_OF_EMP',#	'CUST_REVENUE',	
                         'DAYS_TO_NEXT_RENEWAL',
                         #'END_MRR',#'DOWNGRADE_ARR',  'UPGRADE_ARR', 'END_PROD_CNT'
                         'ARR', 'AVG_ANNUAL_SEATS', 'AVG_MRR', 
                         'AVG_DOWNGRADE_MRR', 'AVG_UPGRADE_MRR',
                         #'AVG_6M_MRR', 'AVG_6M_SEATS', 'AVG_6M_DOWNGRADE_MRR', 'AVG_6M_UPGRADE_MRR',
                         'AVG_3M_MRR', 'AVG_3M_SEATS', 'AVG_3M_DOWNGRADE_MRR', 'AVG_3M_UPGRADE_MRR', 
                         #'AVG_2M_SEATS',#'AVG_2M_MRR',
                         #'AVG_2M_SEATS_PERC','AVG_3M_SEATS_PERC','AVG_6M_SEATS_PERC',
                         #'AVG_2M_MRR_PERC','AVG_3M_MRR_PERC','AVG_6M_MRR_PERC',
                         'PERC_CHANGE_3M_1YR_DOWNGRADE_MRR','PERC_CHANGE_6M_1YR_DOWNGRADE_MRR',
                         'PERC_CHANGE_3M_1YR_UPGRADE_MRR','PERC_CHANGE_6M_1YR_UPGRADE_MRR',      
                         #'PERC_CHANGE_3M_1YR_CALLS_FLAG','PERC_CHANGE_6M_1YR_CALLS_FLAG','PERC_CHANGE_3M_6M_CALLS_FLAG','PERC_CHANGE_3M_1YR_SMS_FLAG','PERC_CHANGE_6M_1YR_SMS_FLAG','PERC_CHANGE_3M_6M_SMS_FLAG',
                         #'PERC_CHANGE_3M_1YR_MEETINGS_FLAG','PERC_CHANGE_6M_1YR_MEETINGS_FLAG','PERC_CHANGE_3M_6M_MEETINGS_FLAG','PERC_CHANGE_3M_1YR_DOWNGRADE_MRR_FLAG','PERC_CHANGE_6M_1YR_DOWNGRADE_MRR_FLAG',      
                         
                        # Last 1 yr case data
                         'O_CHAT_RESOLVED_CNT', 'O_CHAT_WNB_RESOLVED_CNT', 'O_CHAT_CUST_UNRESP_CNT', 'O_CHAT_NOT_RESOLVED_CNT', 'O_PHONE_RESOLVED_CNT', 'O_PHONE_WNB_RESOLVED_CNT', 'O_PHONE_CUST_UNRESP_CNT', 'O_PHONE_NOT_RESOLVED_CNT', 'O_WEB_RESOLVED_CNT', 'O_WEB_WNB_RESOLVED_CNT', 'O_WEB_CUST_UNRESP_CNT', 'O_WEB_NOT_RESOLVED_CNT', 'O_OTHERS_RESOLVED_CNT', 'O_OTHERS_WNB_RESOLVED_CNT', 'O_OTHERS_CUST_UNRESP_CNT', 'O_OTHERS_NOT_RESOLVED_CNT', 
                         'CCC_BILLING_RESOLVED_CNT', 'CCC_BILLING_WNB_RESOLVED_CNT', 'CCC_BILLING_CUST_UNRESP_CNT', 'CCC_BILLING_NOT_RESOLVED_CNT', 'CCC_BUSINESS_CHANGES_RESOLVED_CNT', 'CCC_BUSINESS_CHANGES_WNB_RESOLVED_CNT', 'CCC_BUSINESS_CHANGES_UNRESP_CNT', 'CCC_BUSINESS_CHANGES_NOT_RESOLVED_CNT', 'CCC_BUSINESS_FAIL_RESOLVED_CNT', 'CCC_BUSINESS_FAIL_WNB_RESOLVED_CNT', 'CCC_BUSINESS_FAIL_UNRESP_CNT', 'CCC_BUSINESS_FAIL_NOT_RESOLVED_CNT', 
                         'CCC_DNME_RESOLVED_CNT', 'CCC_DNME_WNB_RESOLVED_CNT', 'CCC_DNME_UNRESP_CNT', 'CCC_DNME_NOT_RESOLVED_CNT', 'CCC_PRICE_RESOLVED_CNT', 'CCC_PRICE_WNB_RESOLVED_CNT', 'CCC_PRICE_UNRESP_CNT', 'CCC_PRICE_NOT_RESOLVED_CNT', 'CCC_FEATURE_RESOLVED_CNT', 'CCC_FEATURE_WNB_RESOLVED_CNT', 'CCC_FEATURE_UNRESP_CNT', 'CCC_FEATURE_NOT_RESOLVED_CNT', 'CCC_SS_RESOLVED_CNT', 'CCC_SS_WNB_RESOLVED_CNT', 'CCC_SS_UNRESP_CNT', 'CCC_SS_NOT_RESOLVED_CNT', 
                         'CCC_SO_RESOLVED_CNT', 'CCC_SO_WNB_RESOLVED_CNT', 'CCC_SO_UNRESP_CNT', 'CCC_SO_NOT_RESOLVED_CNT', 'CCC_QUALITY_RESOLVED_CNT', 'CCC_QUALITY_WNB_RESOLVED_CNT', 'CCC_QUALITY_UNRESP_CNT', 'CCC_QUALITY_NOT_RESOLVED_CNT', 'CCC_OTHERS_RESOLVED_CNT', 'CCC_OTHERS_WNB_RESOLVED_CNT', 'CCC_OTHERS_UNRESP_CNT', 'CCC_OTHERS_NOT_RESOLVED_CNT', 
                         'OVERALL_RESOLVED_CNT','OVERALL_WNB_RESOLVED_CNT','OVERALL_UNRESP_CNT','OVERALL_NOT_RESOLVED_CNT',                    
                         
                        # Last 2M case data
                        'O_CHAT_RESOLVED_CNT_60', 'O_CHAT_WNB_RESOLVED_CNT_60', 'O_CHAT_CUST_UNRESP_CNT_60', 'O_CHAT_NOT_RESOLVED_CNT_60', 'O_PHONE_RESOLVED_CNT_60', 'O_PHONE_WNB_RESOLVED_CNT_60', 'O_PHONE_CUST_UNRESP_CNT_60', 'O_PHONE_NOT_RESOLVED_CNT_60', 'O_WEB_RESOLVED_CNT_60', 'O_WEB_WNB_RESOLVED_CNT_60', 'O_WEB_CUST_UNRESP_CNT_60', 'O_WEB_NOT_RESOLVED_CNT_60', 'O_OTHERS_RESOLVED_CNT_60', 'O_OTHERS_WNB_RESOLVED_CNT_60', 'O_OTHERS_CUST_UNRESP_CNT_60', 'O_OTHERS_NOT_RESOLVED_CNT_60', 
                        'CCC_BILLING_RESOLVED_CNT_60', 'CCC_BILLING_WNB_RESOLVED_CNT_60', 'CCC_BILLING_CUST_UNRESP_CNT_60', 'CCC_BILLING_NOT_RESOLVED_CNT_60', 'CCC_BUSINESS_CHANGES_RESOLVED_CNT_60', 'CCC_BUSINESS_CHANGES_WNB_RESOLVED_CNT_60', 'CCC_BUSINESS_CHANGES_UNRESP_CNT_60', 'CCC_BUSINESS_CHANGES_NOT_RESOLVED_CNT_60', 'CCC_BUSINESS_FAIL_RESOLVED_CNT_60', 'CCC_BUSINESS_FAIL_WNB_RESOLVED_CNT_60', 'CCC_BUSINESS_FAIL_UNRESP_CNT_60', 'CCC_BUSINESS_FAIL_NOT_RESOLVED_CNT_60', 
                        'CCC_DNME_RESOLVED_CNT_60', 'CCC_DNME_WNB_RESOLVED_CNT_60', 'CCC_DNME_UNRESP_CNT_60', 'CCC_DNME_NOT_RESOLVED_CNT_60', 'CCC_PRICE_RESOLVED_CNT_60', 'CCC_PRICE_WNB_RESOLVED_CNT_60', 'CCC_PRICE_UNRESP_CNT_60', 'CCC_PRICE_NOT_RESOLVED_CNT_60', 'CCC_FEATURE_RESOLVED_CNT_60', 'CCC_FEATURE_WNB_RESOLVED_CNT_60', 'CCC_FEATURE_UNRESP_CNT_60', 'CCC_FEATURE_NOT_RESOLVED_CNT_60', 'CCC_SS_RESOLVED_CNT_60', 'CCC_SS_WNB_RESOLVED_CNT_60', 'CCC_SS_UNRESP_CNT_60', 'CCC_SS_NOT_RESOLVED_CNT_60', 
                        'CCC_SO_RESOLVED_CNT_60', 'CCC_SO_WNB_RESOLVED_CNT_60', 'CCC_SO_UNRESP_CNT_60', 'CCC_SO_NOT_RESOLVED_CNT_60', 'CCC_QUALITY_RESOLVED_CNT_60', 'CCC_QUALITY_WNB_RESOLVED_CNT_60', 'CCC_QUALITY_UNRESP_CNT_60', 'CCC_QUALITY_NOT_RESOLVED_CNT_60', 'CCC_OTHERS_RESOLVED_CNT_60', 'CCC_OTHERS_WNB_RESOLVED_CNT_60', 'CCC_OTHERS_UNRESP_CNT_60', 'CCC_OTHERS_NOT_RESOLVED_CNT_60', 'CC_BILLING_RESOLVED_CNT_60', 
                        'OVERALL_RESOLVED_CNT_60','OVERALL_WNB_RESOLVED_CNT_60','OVERALL_UNRESP_CNT_60','OVERALL_NOT_RESOLVED_CNT_60',                    
                        
                          # Max CES Score
                        'MIN_ADOPTION_SCORE','MIN_STICKINESS_SCORE','MIN_MESSAGING_ENGAGEMENT_SCORE','MIN_MEETINGS_ENGAGEMENT_SCORE',                        
                        'MIN_ADOPTION_SCORE_DIFF1',	'MIN_ADOPTION_SCORE_DIFF2',
                        #'MIN_ENGAGEMENT_SCORE_DIFF1',	'MIN_ENGAGEMENT_SCORE_DIFF2',
                        'MIN_STICKINESS_SCORE_DIFF1',	'MIN_STICKINESS_SCORE_DIFF2',	
                        #'MIN_CALL_ENGAGEMENT_SCORE_DIFF1',	'MIN_CALL_ENGAGEMENT_SCORE_DIFF2',
                        #'MIN_CALL_STICK_SCORE_DIFF1',	'MIN_CALL_STICK_SCORE_DIFF2',
                        #'MIN_CALL_ADOPTION_SCORE_DIFF1',	'MIN_CALL_ADOPTION_SCORE_DIFF2',	
                        'MIN_MES_ENG_SCORE_DIFF1',	'MIN_MES_ENG_SCORE_DIFF2',
                        #'MIN_MES_STICK_SCORE_DIFF1',	'MIN_MES_STICK_SCORE_DIFF2',
                        #'MIN_MES_ADOPTION_SCORE_DIFF1',	'MIN_MES_ADOPTION_SCORE_DIFF2',	
                        'MIN_MEETINGS_ENGAGEMENT_SCORE_DIFF1',	'MIN_MEETINGS_ENGAGEMENT_SCORE_DIFF2',
                        #'MIN_MEETINGS_STICKINESS_SCORE_DIFF1',	'MIN_MEETINGS_STICKINESS_SCORE_DIFF2',
                        #'MIN_MEETINGS_ADOPTION_SCORE_DIFF1',	'MIN_MEETINGS_ADOPTION_SCORE_DIFF2'
                        
                        #CALLS USAGE DATA
                        'AVG_TOTAL_CALLS_1YR','AVG_TOTAL_CALLS_3M','PERC_AVG_TOTAL_CALLS_3M','PERC_AVG_TOTAL_CALLS_6M','CALLS_DIFF1','CALLS_DIFF2','CALLS_DIFF3',
                        'AVG_BAD_CALLS_1YR','AVG_BAD_CALLS_3M','PERC_AVG_BAD_CALLS_1YR','PERC_AVG_BAD_CALLS_3M','PERC_AVG_BAD_CALLS_6M','BAD_CALLS_DIFF1','BAD_CALLS_DIFF2',
                        'PERC_CHANGE_3M_1YR_CALLS','PERC_CHANGE_6M_1YR_CALLS','PERC_CHANGE_3M_6M_CALLS',
                        'CURR_MONTH_CALLS','PREV_1MONTH_CALLS','PREV_2MONTH_CALLS',
                        'OUTBOUND_CALLS_DIFF1','OUTBOUND_CALLS_DIFF2','OUTBOUND_CALLS_DIFF3','PERC_CHANGE_3M_1YR_OUTBOUND_CALLS','PERC_CHANGE_6M_1YR_OUTBOUND_CALLS','PERC_CHANGE_3M_6M_OUTBOUND_CALLS',
                        
                         #MESSAGES USAGE DATA
                        'AVG_TOTAL_SMS_1YR','AVG_TOTAL_SMS_3M','SMS_DIFF1','SMS_DIFF2',
                        'PERC_CHANGE_3M_1YR_SMS','PERC_CHANGE_6M_1YR_SMS','PERC_CHANGE_3M_6M_SMS',
                        'CURR_MONTH_MMS','PREV_1MONTH_MMS','PREV_2MONTH_SMS',
                        
                        #MEETINGS DATA
                        'AVG_TOTAL_MEETINGS_1YR','AVG_TOTAL_MEETINGS_3M','MEETINGS_DIFF1','MEETINGS_DIFF2',
                        'PERC_CHANGE_3M_1YR_MEETINGS','PERC_CHANGE_6M_1YR_MEETINGS','PERC_CHANGE_3M_6M_MEETINGS',
                        'CURR_MONTH_MEETINGS','PREV_1MONTH_MEETINGS','PREV_2MONTH_MEETINGS',
                        
                        'CASE_REPEAT_FLAG_7_DAYS_1YR','CASE_REPEAT_FLAG_7_DAYS_6M','CASE_REPEAT_FLAG_7_DAYS_3M',
                        #'CASE_REPEAT_FLAG_30_DAYS_1YR','CASE_REPEAT_FLAG_30_DAYS_6M','CASE_REPEAT_FLAG_30_DAYS_3M',
                        'AVG_CASE_HANDLE_TIME_1YR','AVG_CASE_HANDLE_TIME_6M','AVG_CASE_HANDLE_TIME_3M',
                        'RETENTION_CALL_INDICATOR_1YR','RETENTION_CALL_INDICATOR_6M','RETENTION_CALL_INDICATOR_3M',
                        'SEV1_1YR','SEV1_6M','SEV1_3M','SEV2_1YR','SEV2_6M','SEV2_3M','SEV3_1YR','SEV3_6M','SEV3_3M',
                        'PERC_CHANGE_3M_1YR_ADOPTION_SCORE','PERC_CHANGE_6M_1YR_ADOPTION_SCORE','PERC_CHANGE_3M_6M_ADOPTION_SCORE',
                        'PERC_CHANGE_3M_1YR_STICKINESS_SCORE','PERC_CHANGE_6M_1YR_STICKINESS_SCORE','PERC_CHANGE_3M_6M_STICKINESS_SCORE',
                        'PERC_CHANGE_3M_1YR_MESSAGING_ENGAGEMENT_SCORE','PERC_CHANGE_6M_1YR_MESSAGING_ENGAGEMENT_SCORE','PERC_CHANGE_3M_6M_MESSAGING_ENGAGEMENT_SCORE',
                        'PERC_CHANGE_3M_1YR_MEETINGS_ENGAGEMENT_SCORE_SCORE','PERC_CHANGE_6M_1YR_MEETINGS_ENGAGEMENT_SCORE_SCORE','PERC_CHANGE_3M_6M_MEETINGS_ENGAGEMENT_SCORE_SCORE'

                        
                           ])], remainder='passthrough')

# Transforming data
X_scaled = ct.fit_transform(X_train)
X_test_scaled = ct.transform(X_test)

cols=X_train.columns

X_scaled = pd.DataFrame(X_scaled, columns=[cols])
X_test_scaled = pd.DataFrame(X_test_scaled, columns=[cols])


##################################################################################################################################################################################################################################################################
######################################_____________Training_Model______________####################################################################################################################################################################################################################################################################################################################


# Defining the range of hyperparameters to search
param_grid = {
    'C': [0.001, 0.01, 0.1, 1, 10, 100, 1000, 1250], 
    'solver': ['liblinear'],  
    'penalty': ['l1','l2']   
}

# Create a logistic regression model
logistic_regression = LogisticRegression(random_state=42, max_iter=1000)

print("starting grid serch")
# Perform grid search with cross-validation
grid_search = GridSearchCV(logistic_regression, param_grid, cv=5, scoring='accuracy',n_jobs=-1)
print("stp 1")
grid_search.fit(X_train, y_train)
print("stp 2")
# Get the best hyperparameters
best_params = grid_search.best_params_
print("Best Hyperparameters:", best_params)

# # Train the final model with the best hyperparameters
final_classifier = LogisticRegression(**best_params, max_iter=10000)
final_classifier.fit(X_scaled, y_train)

y_pred = final_classifier.predict(X_test_scaled)
# # Evaluate the model
accuracy = accuracy_score(y_test, y_pred)

# Generate a classification report
report = classification_report(y_test, y_pred)
print("Accuracy on test set:", accuracy)

print(f"Accuracy: {accuracy}")
print(f"Classification Report:\n{report}")


##################################################################################################################################################################################################################################################################
######################################_____________Pickling_Model______________####################################################################################################################################################################################################################################################################################################################


with open('model_srikanth.pkl', 'wb') as f:
    pickle.dump(final_classifier, f)

s3 = boto3.client('s3')
file = "model_srikanth.pkl"
bucket = "sanjeev-churn-pred-test"
s3_key = "model_srikanth.pkl"

try:
    s3.upload_file(file, bucket, s3_key)
except Exception as e:
    print(e)












